In [1]:
import numpy as np
import pandas as pd
from datetime import date

In [85]:
# CMT250 = pd.read_excel(r'C:\Users\User\VSCode\M13226\CDSS.xlsx', sheet_name='CMT250')
# Report = pd.read_excel(r'C:\Users\User\VSCode\M13226\CDSS.xlsx', sheet_name='微生物報告')
# Value = pd.read_excel(r'C:\Users\User\VSCode\M13226\CDSS.xlsx', sheet_name='檢驗數值')
mdro_1 = pd.read_excel(r'C:\Users\User\VSCode\智抗菌平台統計(20211201-20220119)_OV.xlsx', sheet_name='MDROs', 
                        dtype={'病歷號碼':'str', '申請編號':'int', '就醫序號':'int'})
report_1 = pd.read_excel(r'C:\Users\User\VSCode\智抗菌平台統計(20211201-20220119)_OV.xlsx', sheet_name='微生物報告', 
                        dtype={'病歷號碼':'str', '申請編號':'int', '就醫序號':'int'})
mdro_2 = pd.read_excel(r'C:\Users\User\VSCode\智抗菌平台報表_20220210.xlsx', sheet_name='MDROs', 
                        dtype={'病歷號碼':'str', '申請編號':'int', '就醫序號':'int'})
report_2 = pd.read_excel(r'C:\Users\User\VSCode\智抗菌平台報表_20220210.xlsx', sheet_name='微生物報告', 
                        dtype={'病歷號碼':'str', '申請編號':'int', '就醫序號':'int'})

In [86]:
# MDRO's & 微生物報告

mdro_1 = mdro_1[['病歷號碼', 'time', '就醫序號', '申請編號', '菌株', '預測值', '部位(所有部位)', '資訊室資料發送時間']]
mdro_1.rename({'time':'openTime', '部位(所有部位)':'部位', '資訊室資料發送時間':'sendTime'}, axis=1, inplace=True)

In [87]:
# mdro_1['就醫序號']

0      231557756
1      231610815
2      231610815
3      231610815
4      231610815
         ...
872    232398080
873    232398080
874    232400173
875    232033200
876    232351128
Name: 就醫序號, Length: 877, dtype: int32

In [88]:
report_1 = report_1[['病歷號碼', 'bed', '就醫序號', '申請編號', '部位', '抗藥性菌株', 'reportTime(發報告時間)']]
report_1.rename({'reportTime(發報告時間)':'reportTime'}, axis=1, inplace=True)
report_1

            病歷號碼 bed       就醫序號       申請編號    部位  抗藥性菌株        reportTime
0     0036723942  住院  168822972  393623588     S    NaN  2020-12-11 10:27
1     0021234304  住院  168355808  393626701     B    NaN  2020-12-14 12:00
2     0000117232  住院  168292950  393626846    AS    NaN  2020-12-12 14:26
3     0000117232  住院  168292950  393626847    AS    1.0  2020-12-12 14:26
4     0000117232  住院  168292950  393626848    AS    1.0  2020-12-12 14:26
...          ...  ..        ...        ...   ...    ...               ...
7280  0000576498  住院  232226923  393939370   SCO    NaN  2022-01-19 16:26
7281  0023630273  急診  232368607  393939413     B    NaN  2022-01-19 14:04
7282  0028373927  住院  231880332  393939166  PUSS    NaN  2022-01-19 13:16
7283  0023790715  急診  232389293  393939737     B    NaN  2022-01-19 16:19
7284  0022936930  住院  232291217  393940205    SP    NaN  2022-01-19 16:28

[7285 rows x 7 columns]

In [89]:
mdro_2 = mdro_2[['病歷號碼', 'time', '就醫序號','申請編號', '菌株', '預測值', '部位', 'sendTime']]
mdro_2.rename({'time':'openTime'}, axis=1, inplace=True)
mdro_2

,病歷號碼,openTime,就醫序號,申請編號,菌株,預測值,部位,sendTime
0,0022339892,2022-01-25 08:38:47,232235955,393941020,Enterococcus faecium,100,CA,2022-01-22 14:52:14
1,0022339892,2022-01-25 08:39:32,232235955,393941020,Enterococcus faecium,100,CA,2022-01-22 14:52:14
2,0000548843,2022-01-25 09:24:01,232101055,393942462,Klebsiella pneumoniae,10,PUSS,2022-01-24 13:00:09
3,0000548843,2022-01-25 09:24:01,232101055,393942069,Acinetobacter baumannii,10,SET,2022-01-22 14:52:14
4,0000147257,2022-01-25 10:29:28,232438952,393942472,Escherichia coli,10,UM,2022-01-24 14:33:35
...,...,...,...,...,...,...,...,...
1447,0015844041,2022-01-19 16:47:21,232398080,393938013,Enterobacter cloacae,10,UC,2022-01-18 14:02:10
1448,0015844041,2022-01-19 17:09:47,232398080,393938013,Enterobacter cloacae,10,UC,2022-01-18 14:02:10
1449,0000221398,2022-01-19 17:21:43,232400173,393937104,Escherichia coli,10,UC,2022-01-17 14:52:02
1450,0021809094,2022-01-19 17:50:51,232033200,393939128,Staphylococcus aureus,60,DP,2022-01-19 12:02:05
1451,0019655180,2022-01-19 20:39:59,232351128,393938063,Pseudomonas aeruginosa,10,SET,2022-01-19 13:52:07

In [90]:
report_2 = report_2[['病歷號碼', 'bed', '就醫序號','申請編號', '部位', '抗藥性菌株', 'reportTime']]
report_2

            病歷號碼 bed       就醫序號       申請編號  部位  抗藥性菌株        reportTime
0     0014370701  門診  166496412  393594588  UM    NaN  2020-11-23 14:33
1     0036723942  住院  168822972  393623588   S    NaN  2020-12-11 10:27
2     0021234304  住院  168355808  393626701   B    NaN  2020-12-14 12:00
3     0030173329  住院  168905057  393627026   B    NaN  2020-12-14 08:12
4     0021234304  住院  168355808  393628286  DP    NaN  2020-12-14 11:59
...          ...  ..        ...        ...  ..    ...               ...
4192  0025276515  住院  232408284  393953977   B    NaN  2022-02-10 09:26
4193  0038080368  急診  232635263  393954134   B    NaN  2022-02-10 09:27
4194  0038080368  急診  232635263  393954135   B    NaN  2022-02-10 09:27
4195  0030045964  急診  232636359  393954201   B    NaN  2022-02-10 09:27
4196  0030045964  急診  232636359  393954202   B    NaN  2022-02-10 09:27

[4197 rows x 7 columns]

In [91]:
cdss_1 = pd.merge(report_1, mdro_1, how='left', on=['病歷號碼', '就醫序號','申請編號', '部位'])
cdss_2 = pd.merge(report_2, mdro_2, how='left', on=['病歷號碼', '就醫序號','申請編號', '部位'])
# cdss_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4578 entries, 0 to 4577
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   病歷號碼        4578 non-null   object
 1   bed         4578 non-null   object
 2   就醫序號        4578 non-null   int32
 3   申請編號        4578 non-null   int32
 4   部位          4578 non-null   object
 5   抗藥性菌株       1006 non-null   float64
 6   reportTime  4578 non-null   object
 7   openTime    680 non-null    object
 8   菌株          680 non-null    object
 9   預測值         680 non-null    float64
 10  sendTime    600 non-null    object
dtypes: float64(2), int32(2), object(7)
memory usage: 393.4+ KB

In [92]:
cdss_1 = cdss_1.drop_duplicates()
cdss_2 = cdss_2.drop_duplicates()

In [93]:
cdss_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4577 entries, 0 to 4577
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   病歷號碼        4577 non-null   object
 1   bed         4577 non-null   object
 2   就醫序號        4577 non-null   int32
 3   申請編號        4577 non-null   int32
 4   部位          4577 non-null   object
 5   抗藥性菌株       1005 non-null   float64
 6   reportTime  4577 non-null   object
 7   openTime    679 non-null    object
 8   菌株          679 non-null    object
 9   預測值         679 non-null    float64
 10  sendTime    599 non-null    object
dtypes: float64(2), int32(2), object(7)
memory usage: 393.3+ KB

In [110]:
CDSS = pd.concat([cdss_1, cdss_2],axis=0)
CDSS = CDSS.drop_duplicates()

# 如同一菌株預測多筆，則選第一筆出現
CDSS['minTime'] = CDSS.groupby(['病歷號碼', 'bed','就醫序號', '申請編號', '部位', '菌株', '預測值',  'sendTime'])['openTime'].transform('min')

In [95]:
# 抗生素使用
anti = pd.read_excel(r'C:\Users\User\VSCode\智抗菌平台報表_20220210.xlsx', sheet_name='抗生素使用', 
                        dtype={'病歷號碼':'str', '就醫序號':'int'})

In [118]:
CDSS_Anti = pd.merge(CDSS, anti, how='left', on=['病歷號碼','就醫序號'])
CDSS_Anti = CDSS_Anti.drop_duplicates()
CDSS_Anti.info()

# CDSS_Anti.to_excel(r'C:\Users\User\VSCode\CDSS_20220316.xlsx')

In [113]:
# CDSS_Anti[CDSS_Anti['openTime']==CDSS_Anti['minTime']]

,病歷號碼,bed,就醫序號,申請編號,部位,抗藥性菌株,reportTime,openTime,菌株,預測值,...,minTime,類別,醫令代碼,每次量,途徑,頻率,使用天數,開始時間,截止時間,囑咐
5618,0017161189,住院,231557756,393899033,UM,1.0,2021-12-01 10:50,2021-12-01 10:34:03,Enterococcus faecium(VRE),100.0,...,2021-12-01 10:34:03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5739,0036840653,住院,231447351,393900398,B,NaN,2021-12-02 08:39,2021-12-01 11:37:14,Staphylococcus aureus,10.0,...,2021-12-01 11:37:14,住院用藥,TNYSTAT1,10.0,GAR,STAT,1.0,2021-11-21 23:16,2021-11-21 23:16,FOR GAR
5740,0036840653,住院,231447351,393900398,B,NaN,2021-12-02 08:39,2021-12-01 11:37:14,Staphylococcus aureus,10.0,...,2021-12-01 11:37:14,住院用藥,IMEROPE,2.0,IVD,STAT,1.0,2021-11-28 10:40,2021-11-28 10:40,pnuemonia 釋液:NS;總量:100mL;時間:30分;流速:200mL/hr;
5741,0036840653,住院,231447351,393900398,B,NaN,2021-12-02 08:39,2021-12-01 11:37:14,Staphylococcus aureus,10.0,...,2021-12-01 11:37:14,住院用藥,ISEPTRI,1.0,IVD,STAT,1.0,2021-11-29 00:38,2021-11-29 00:38,釋液:NS;總量:125mL;時間:90分;流速:83mL/hr; for suspect...
5742,0036840653,住院,231447351,393900398,B,NaN,2021-12-02 08:39,2021-12-01 11:37:14,Staphylococcus aureus,10.0,...,2021-12-01 11:37:14,住院用藥,ISEPTRI,5.0,IVD,STAT,1.0,2021-11-29 03:38,2021-11-29 03:38,釋液:NS;總量:450mL;時間:90分;流速:300mL/hr; for suspect...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31338,0030328599,住院,231696873,393953443,UC,NaN,2022-02-10 08:02,2022-02-09 20:10:51,Escherichia coli,10.0,...,2022-02-09 20:10:51,住院用藥,ICEFAZO2,1.0,IVD,STAT,1.0,2022-01-04 10:01,2999-12-31 00:00,釋液:NS;總量:50mL;時間:30分;流速:100mL/hr;preventive an...
31339,0030328599,住院,231696873,393953443,UC,NaN,2022-02-10 08:02,2022-02-09 20:10:51,Escherichia coli,10.0,...,2022-02-09 20:10:51,住院用藥,IFLOMOX1,1.0,IVD,STAT,1.0,2022-01-19 14:10,2999-12-31 00:00,釋液:NS;總量:100mL;時間:30分;流速:200mL/hr;UTI
31340,0030328599,住院,231696873,393953443,UC,NaN,2022-02-10 08:02,2022-02-09 20:10:51,Escherichia coli,10.0,...,2022-02-09 20:10:51,住院用藥,ITAZOCI1,1.5,IVD,STAT,1.0,2022-02-09 03:36,2999-12-31 00:00,釋液:NS;總量:75mL;時間:30分;流速:150mL/hr;UTI
31341,0030328599,住院,231696873,393953443,UC,NaN,2022-02-10 08:02,2022-02-09 20:10:51,Escherichia coli,10.0,...,2022-02-09 20:10:51,住院用藥,IANIDUL,2.0,IVD,STAT,1.0,2022-02-09 10:08,2999-12-31 00:00,釋液:NS;總量:200mL;時間:180分;流速:67mL/hr;Immuncomprom...
31342,0030328599,住院,231696873,393953443,UC,NaN,2022-02-10 08:02,2022-02-09 20:10:51,Escherichia coli,10.0,...,2022-02-09 20:10:51,住院用藥,IAMIKAC,1.6,IVD,STAT,1.0,2022-02-09 20:16,2999-12-31 00:00,釋液:NS;總量:80mL;時間:30分;流速:160mL/hr;

In [108]:
# 死亡檔
death_1 = pd.read_excel(r'C:\Users\User\VSCode\智抗菌_死亡_0223.xlsx',sheet_name='202101-06明細', dtype={'病歷號碼':'str'})
death_2 = pd.read_excel(r'C:\Users\User\VSCode\智抗菌_死亡_0223.xlsx',sheet_name='202107-12明細', dtype={'病歷號碼':'str'})
death_3 = pd.read_excel(r'C:\Users\User\VSCode\智抗菌_死亡_0223.xlsx',sheet_name='202201明細', dtype={'病歷號碼':'str'})

In [116]:
death = pd.concat([death_1, death_2, death_3], axis=0)
death['row_number']=death.groupby(['病歷號'])['病歷號'].cumcount()

In [117]:
death

,住院號,註記,費用年月,病歷號,住院日,出院日,轉歸Indtrout,藥費Indfee51,實際醫療費用Indtotal,主診,...,次診17_name,次診18,次診18_name,次診19,次診19_name,TW-DRG,RW,次診13_name,Key,row_number
0,1563815,*,11001,27645890,1091227,1100101,3,10250,24914,J441,...,NaN,,NaN,,NaN,08802,0.5386,NaN,NaN,0
1,1564224,*,11001,36795772,1091229,1100102,3,1171,48309,S72322A,...,NaN,,NaN,,NaN,21103,1.3616,NaN,NaN,0
2,1564758,*,11001,36332001,1091230,1100102,3,3153,18133,O6003,...,NaN,,NaN,,NaN,37903,0.4218,NaN,NaN,0
3,1564858,*,11001,24380673,1091231,1100103,3,803,11063,L259,...,NaN,,NaN,,NaN,28301,0.4309,NaN,NaN,0
4,1564151,*,11001,25021383,1091228,1100104,3,10469,30856,L0211,...,NaN,,NaN,,NaN,277,0.641,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,1653258,*,11101,27777495,1110119,1110127,1,10713,48074,Z5111,...,NaN,,NaN,,NaN,YYY,YYY,NaN,0027777495_1110127,0
4,1653468,*,11101,22046224,1110120,1110127,3,3529,57000,K5660,...,NaN,,NaN,,NaN,180,0.5225,NaN,0022046224_1110127,0
5,1653562,*,11101,14097,1110120,1110128,3,14157,131379,A412,...,NaN,,NaN,,NaN,41501,2.1658,NaN,0000014097_1110128,0
6,1653381,*,11101,18975094,1110119,1110129,3,23710,98917,I132,...,NaN,,NaN,,NaN,12702,0.7359,NaN,0018975094_1110129,0
7,1654856,*,11101,11039748,1110125,1110130,3,7377,32936,J860,...,NaN,,NaN,,NaN,07904,1.1079,NaN,0011039748_1110130,0